name: Cypress Tests
on:
  push:
    branches: [master]
  pull_request:
     branches: [master]
jobs: 
  cypress-run: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npx cypress open
    
         
