name: run-on-docker
on:
  push:
    branches: [main]
  pull_request:
     branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v1
      - run: cypress-io/github-action@v4.x.x



    
         
